set(_CATKIN_CURRENT_PACKAGE "biobot_ros_msgs")
set(biobot_ros_msgs_VERSION "0.0.0")
set(biobot_ros_msgs_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(biobot_ros_msgs_PACKAGE_FORMAT "1")
set(biobot_ros_msgs_BUILD_DEPENDS "roscpp" "rospy" "message_runtime")
set(biobot_ros_msgs_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "message_runtime")
set(biobot_ros_msgs_BUILDTOOL_DEPENDS "catkin")
set(biobot_ros_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(biobot_ros_msgs_EXEC_DEPENDS "roscpp" "rospy" "message_runtime")
set(biobot_ros_msgs_RUN_DEPENDS "roscpp" "rospy" "message_runtime")
set(biobot_ros_msgs_TEST_DEPENDS )
set(biobot_ros_msgs_DOC_DEPENDS )
set(biobot_ros_msgs_DEPRECATED "")